# Generated by Django 4.1.1 on 2022-11-23 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_about_alter_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Username cannot exceed 100 characters.', 'min_length': 'username needs to be at least 5 characters long.', 'unique': 'An user with that name already exists.'}, help_text='Username needs to be between 5 and 100 characters.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='username'),
        ),
    ]
