# Generated by Django 4.1.1 on 2022-12-26 14:07

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='uProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, upload_to=accounts.models.UserProfile.profile_pic_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions={'png', 'tiff', 'jpeg', 'gif', 'bitmap', 'jpg'}, message='Only these extensions are allowed:- .jpeg, .jpg, .bitmap, .png, .gif, .tiff')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
