# Generated by Django 4.1.1 on 2022-12-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_uprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uProfile',
            new_name='UserProfile',
        ),
    ]
