# Generated by Django 4.1.1 on 2022-12-27 08:43

from django.db import migrations


def transfer_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in User.objects.all():
        if UserProfile.objects.filter(user=user).exists():
            inst = UserProfile.objects.get(user=user)
            if inst.profile_picture == '':
                inst.profile_picture = user.profile_pic
                inst.save(update_fields=['profile_picture'])
        else:
            uf = UserProfile.objects.create(user=user, profile_picture=user.profile_pic)
            print(uf)
        

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_subscribers_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
