# Generated by Django 4.1.1 on 2022-12-27 14:47

from django.db import migrations


def transfer(apps, schema_editor):
    Subscription = apps.get_model('youplay', 'subscription')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for profile in UserProfile.objects.all():
        subscriptions = profile.user.subscribed_to.all()
        subscribers = profile.user.subscribers.all()
        if subscriptions.count() != 0:
            for subscription in subscriptions:
                profile.subscriptions.add(subscription.subscribed_to)
        if subscribers.count() != 0:
            for subscriber in subscribers:
                profile.subscribers.add(subscriber.subscriber)
                

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_auto_20221227_0843'),
        ('youplay', '0010_subscription_unique_subscription')
    ]

    operations = [
        migrations.RunPython(transfer)
    ]
