# Generated by Django 4.1.1 on 2022-12-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
