# Generated by Django 4.1.1 on 2023-03-14 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_userprofile_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
