# Generated by Django 4.1.1 on 2023-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="about",
            field=models.TextField(
                blank=True, help_text="4000 characters maximum.", max_length=4000
            ),
        ),
    ]
