# Generated by Django 4.1.1 on 2023-04-20 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_remove_userprofile_subscribers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "An user with that email already exists."},
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Enter a valid email address"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "max_length": "Username cannot exceed 100 characters.",
                    "min_length": "username needs to be at least 5 characters long.",
                    "unique": "An user with that name already exists.",
                },
                help_text="Username needs to be between 3 and 30 characters. Besides letters and numbers, only _, -, . and @ are allowed  ",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(30),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9\\_\\-\\.@]+$",
                        "Besides letters and numbers only _, -, . and @ are allowed, no spaces too.",
                    ),
                ],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="4000 characters maximum.",
                max_length=4000,
                validators=[django.core.validators.MaxLengthValidator(4000)],
            ),
        ),
    ]
