# Generated by Django 4.1.1 on 2022-11-23 16:46

import django.core.validators
from django.db import migrations, models
import youplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('youplay', '0002_watchlater_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='5000 characters maximum.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Only these extensions are allowed:- .jpg, .jpeg, .bmp, .gif, .tiff', upload_to=youplay.models.Video.thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'tiff'], message='Only these extensions are allowed:- .jpg, .jpeg, .bmp, .gif, .tiff')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
