# Generated by Django 4.1.1 on 2022-12-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youplay', '0005_alter_playlist_options_alter_comment_commenter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-name']},
        ),
    ]
