# Generated by Django 4.1.1 on 2022-12-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youplay', '0007_alter_subscription_subscribed_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['timestamp']},
        ),
    ]
