# Generated by Django 4.1.1 on 2022-12-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youplay', '0008_alter_playlist_options_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title', '-timestamp']},
        ),
    ]
