# Generated by Django 4.1.1 on 2022-12-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youplay', '0012_alter_video_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
