# Generated by Django 4.1.1 on 2023-03-26 07:04

import django.core.validators
from django.db import migrations, models
import youplay.models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0014_alter_like_options_alter_playlist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Allowed extensions are:- .jpg, .jpeg, .bmp, .gif, .tiff.",
                upload_to=youplay.models.Video.thumbnail_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "bmp", "gif", "tiff"],
                        message="Only these extensions are allowed:- .jpg, .jpeg, .png, .bmp, .gif, .tiff.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                help_text="Allowed extensions are:- .mp4, .avi, .mkv, .mov, .wmv, .webm, .ogg, .flv, .3gp, .mkv, .m4a.",
                upload_to=youplay.models.Video.video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "avi",
                            "mkv",
                            "mov",
                            "wmv",
                            "webm",
                            "ogg",
                            "flv",
                            "3gp",
                            "mkv",
                            "m4a",
                        ],
                        message="Only these extensions are allowed:- .mp4, .avi, .mkv, .mov, .wmv, .webm, .ogg, .flv, .3gp, .mkv, .m4a.",
                    )
                ],
            ),
        ),
    ]
