# Generated by Django 4.1.1 on 2023-03-27 07:47

import django.core.validators
from django.db import migrations, models
import youplay.models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0015_alter_video_thumbnail_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Allowed extensions are:- .jpg, .jpeg, .png, .bmp, .gif, .tiff.",
                upload_to=youplay.models.Video.thumbnail_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "bmp", "gif", "tiff"],
                        message="Only these extensions are allowed:- .jpg, .jpeg, .png, .bmp, .gif, .tiff.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                help_text="Title cannot be longer than 100 characters.", max_length=100
            ),
        ),
    ]
