# Generated by Django 4.1.1 on 2023-03-27 08:47

import django.core.validators
from django.db import migrations, models
import youplay.models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0016_alter_video_thumbnail_alter_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                error_messages={"max_length": "Maximum of 4000 characters allowed."},
                help_text="4000 characters maximum.",
                max_length=4000,
                validators=[django.core.validators.MaxLengthValidator(4000)],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                error_messages={"invalid_extension": "blah bleh blah"},
                help_text="Allowed extensions are:- .jpg, .jpeg, .png, .bmp, .gif, .tiff.",
                upload_to=youplay.models.Video.thumbnail_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "bmp", "gif", "tiff"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                error_messages={"max_length": "Title cannot exceed 100 characters"},
                help_text="Title cannot be longer than 100 characters.",
                max_length=100,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
    ]
