# Generated by Django 4.1.1 on 2023-03-27 13:27

import django.core.validators
from django.db import migrations, models
import youplay.models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0017_alter_video_description_alter_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                error_messages={"invalid_extension": "blah bleh blah"},
                help_text="Allowed extensions are:- .jpg, .jpeg, .png, .bmp, .gif, .tiff.",
                upload_to=youplay.models.Video.thumbnail_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "svg",
                            "bmp",
                            "gif",
                            "tiff",
                        ]
                    )
                ],
            ),
        ),
    ]
