# Generated by Django 4.1.1 on 2023-03-31 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0018_alter_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                error_messages={
                    "max_length": "Description cannot exceed 4000 characters."
                },
                help_text="4000 characters maximum.",
                max_length=4000,
                validators=[django.core.validators.MaxLengthValidator(4000)],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                error_messages={
                    "max_length": "Title cannot exceed 100 characters",
                    "min_length": "Title cannot be less than 3 characters.",
                },
                help_text="Title cannot be longer than 100 characters.",
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(100),
                ],
            ),
        ),
    ]
