# Generated by Django 4.1.1 on 2023-04-01 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0019_alter_playlist_name_alter_video_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
