# Generated by Django 4.1.1 on 2023-04-03 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0020_alter_playlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(
                help_text="your comment cannot be more than 500 characters",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
