# Generated by Django 4.1.1 on 2023-04-13 06:08

import django.core.validators
import youplay.models
import youplay.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0025_alter_video_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                help_text="Allowed extensions are:- .mp4, .avi, .mkv, .mov, .wmv, .webm, .ogg, .flv, .3gp, .mkv",
                upload_to=youplay.models.Video.video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "avi",
                            "mkv",
                            "mov",
                            "wmv",
                            "webm",
                            "ogg",
                            "flv",
                            "3gp",
                            "mkv",
                            "m4a",
                        ],
                        message="Only these extensions are allowed:- .mp4, .avi, .mkv, .mov, .wmv, .webm, .ogg, .flv, .3gp, .mkv",
                    ),
                    youplay.utils1.is_valid_video,
                ],
            ),
        ),
    ]
