# Generated by Django 4.1.1 on 2023-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0029_video_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
