# Generated by Django 4.2.5 on 2023-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("youplay", "0033_convertedfilenames"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("registered_on", models.DateField()),
                (
                    "account_type",
                    models.CharField(
                        choices=[("R", "Regular"), ("G", "Gold"), ("P", "Platinum")],
                        default="R",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConvertedFilenames",
        ),
    ]
